env:
  global:
  - secure: S4pmqyq048Pm+NJqeLSvZi1iblX+afVAaJy2VsNg3gAN6vnb9eiIYnPLKFNAA/N7MC1z2lhGJ9EHZ9DLxAgdv+zAUGHmHnwUissye1kavmTWPGRTB4l5Ng7nermanBAg/+a4dk9BhrOEXo7CdzY6+A5jCKny2TNsT8QeOonXUMgBYn6+spnKuCVklhOM2beZCTJfyJY3DMbt4cpUkXDce8FWlpyfI/fRIA2gbdf+HpiW0VywciHBryNzsNj7RLHjnyg8ScZdno8mFEVMfSRsSQJ+1qfs3inkYI83jxL27MIAztG14JJnVUzC6xdfu5xCN6mXEtRmOZfb3WqFhthzEaYcd1J2cly0PTHYefsUACFj6B0MVV+R3244sPGJF3q7whGuT7W9miqbJvhcDj1Mp9vGi69mIbTSgXCVfNN2Z3S7qw3yJsk5EnE/7aaSaHGvuRY4s11stpSDDsgYpAKFPdrsUksTbx5PGXYqXYCrKHLFjt6SOy0RsQuzgMxhUOt9IXjxo76xa6VsY4E3desQp/hL7B1ZFTu/43+JkNs8Za/3nniP2FJZ8vu/+S5PaAloSjUu13zWd+8cM4NnVt8zyOdngSwcZksInqMzN046wURsxKqGRghCMhvCppvbdMdvQAjX+o1EBvcvng0FToW3Thj6RObicJjF/3b+WXbMzV8=

dist: trusty

language: node_js
node_js:
- lts/*

addons:
  sonarcloud:
    organization: psmorrow-github
    token:
      secure: iLmf7Tx0zHPh7Jd9jM3xGDhua2fyb5qLTkRhkFJisenbgZ69SXEcA7ihc1jParZneYNKeRx/aFBJD16x6lo+kbiuyckb1HKnw+VFoDS1Rjy2LfLWG2I4PlyQisu+mwAth5/oCoYjU1nKMQPUUMIPbBCxCMdcQ+N0On9+KwVEIv6Ahj7nJDK45QCNKF4DNSmxYwuw/EQYsMtni/B8IGRyM3Cz03yrPs1qkrnaOqs7YXb7O47S7zBJmoe6I5Japev3YAF2qOn4LJxqTkq715PIk5O0L2cCWEi3/kz/W4WZpskm75rGdyGOI6ItyCq80+fgGHaIxGNuoEI4fkkfkxg8MISFMC37JrJyKSzUBVmvSDOZ+f/YbSsm1u7eZCtFgzPy0FD7Fv2/2Fh4G7T0EVGkQFF8eY44afxo9yOqviv1FjiOLZh+1dYQW2zLDFRBkroOpnUxFEFe6DasCFOs+ipDCkuUBZSdOpNNSjCiTF3DvycmdTooRLLq1Mkmg2RU5tjFkTSrnjdzLnJ5yEY9/RYORbjgsfNoPLKSvgT4mtr90Ft3njXVpalpwgvvZRL3/5wHo+ATWjAl6ZR13cS04nz/nVxiIS8wE4dmW446tjEHOn6KRmwmS3OLH0wYwBSe6IhOOR7RQHMaMzywrF4D12SUZe49qSeFiY3Wl6MpfRR5Hu4=
  coverity_scan:
    project:
      name: "psmorrow/vulnerable-web-application"
      description: "Vulnerable Web Application"
    notification_email: pat@themorrowgroup.com
    build_command_prepend: ""
    build_command: "--no-command --fs-capture-search ./ --fs-capture-search-exclude-regex coverage --fs-capture-search-exclude-regex node_modules"
    branch_pattern: master

before_install:
- npm version 1.0.$TRAVIS_BUILD_NUMBER
- sed -i -e "s/sonar.projectVersion=1.0.0/sonar.projectVersion=1.0.$TRAVIS_BUILD_NUMBER/g" sonar-project.properties
- echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

script:
- npm run lint
- npm test
- sonar-scanner
