env:
  global:
  - secure: "Z+RZWE1wGFDFJVRom7psEmdqu2mvaYWmTx4o4/9a2aUCh5lLsbyCKiHH96iJ35sG6+LIIDIhqN+fCqhVlJf3YsHZxWXp6ZotzAowWkO7skUlVOJCyMED8rLQNu71fsoG8f0+LZ88/mKcUNB7N2Esuuzj9+OJCYpS+GCatUdnMTGHmB4lF1Q9lrYI0/qwaQzxaIEEKXM0BvraLDzHJD//2lVULmv6fvp2U1zwTytZXuPKqg+bcPbsbOG33VGWj0ndeMVxn27xTp04rN5s5A3csblKLcQxFC0x56q3PidQ78ihQ1A4cKMWk9sJlKmRTef4Sj4z+F+B195ez6GCbx7hf49AIl3dJX3Zb7LoajyT89eqPScmOejvfz08ywDLQC/oVlwS9H1JOiXJzmURBJ0y/KfL/1F/i2r75c4xy7xtUkP+JwKLdgX82YlQLsL+WznoT1XJYs7bMUrjc/fL0RfQNJsZ93sm21JYaRpM24KhbAsKdUpGjqKT7ylsbwbeYqDY/9CboK4zo/aGYv3m0/k9StUr6EeXXr5FG18B80b7UkuUcOZCo0HQ3R3oDZ/5uTJ9nAV5yIkEofqkzV7r6Mnu0yihH5vhjz9WfGSlEhjhlwm3GDjQS75zlY1Cdh9Kp44nJzy6s7x9UQg2dWtKJo/r3dZKHUglWeH+vdAfUYgb9/g="

dist: trusty

language: node_js
node_js:
- lts/*

#addons:
#  sonarcloud:
#    organization: psmorrow-github
#    token:
#      secure: iLmf7Tx0zHPh7Jd9jM3xGDhua2fyb5qLTkRhkFJisenbgZ69SXEcA7ihc1jParZneYNKeRx/aFBJD16x6lo+kbiuyckb1HKnw+VFoDS1Rjy2LfLWG2I4PlyQisu+mwAth5/oCoYjU1nKMQPUUMIPbBCxCMdcQ+N0On9+KwVEIv6Ahj7nJDK45QCNKF4DNSmxYwuw/EQYsMtni/B8IGRyM3Cz03yrPs1qkrnaOqs7YXb7O47S7zBJmoe6I5Japev3YAF2qOn4LJxqTkq715PIk5O0L2cCWEi3/kz/W4WZpskm75rGdyGOI6ItyCq80+fgGHaIxGNuoEI4fkkfkxg8MISFMC37JrJyKSzUBVmvSDOZ+f/YbSsm1u7eZCtFgzPy0FD7Fv2/2Fh4G7T0EVGkQFF8eY44afxo9yOqviv1FjiOLZh+1dYQW2zLDFRBkroOpnUxFEFe6DasCFOs+ipDCkuUBZSdOpNNSjCiTF3DvycmdTooRLLq1Mkmg2RU5tjFkTSrnjdzLnJ5yEY9/RYORbjgsfNoPLKSvgT4mtr90Ft3njXVpalpwgvvZRL3/5wHo+ATWjAl6ZR13cS04nz/nVxiIS8wE4dmW446tjEHOn6KRmwmS3OLH0wYwBSe6IhOOR7RQHMaMzywrF4D12SUZe49qSeFiY3Wl6MpfRR5Hu4=
addons:
  coverity_scan:
    project:
      name: "psmorrow/vulnerable-web-application"
      description: "Vulnerable Web Application"
    notification_email: pat@themorrowgroup.com
    build_command_prepend: ""
    build_command: "--dir id --fs-capture-search . --no-command"
    branch_pattern: master

before_install:
- npm version 1.0.$TRAVIS_BUILD_NUMBER
- sed -i -e "s/sonar.projectVersion=1.0.0/sonar.projectVersion=1.0.$TRAVIS_BUILD_NUMBER/g" sonar-project.properties
- echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

script:
- npm run lint
- npm test
#- sonar-scanner
